[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libudev-dev:$CROSS_DEB_ARCH",
]


[build]
# Raspberry Pi 0/1
# target = "arm-unknown-linux-gnueabihf"
# Raspberry Pi 2/3/4
target = "aarch64-unknown-linux-musl"
